### ISSUE TITLE
make venv error

### ISSUE THREAD

**Issue by alanocallaghan** [sabagh1994/BEDwARS#1]
Hey, trying to check out your method - seems very nice.

I get an error trying to make the python venv: 

```
(venv) alan@alan-Z87MX-D3H:~/Documents/github/wallace/BEDwARS/ (main) $ make venv 
python -m venv venv
source venv/bin/activate && python -m pip install --upgrade pip
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.3)
source venv/bin/activate && python -m pip install torch==1.8.1+cu111 \
	-f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu111 (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, 1.11.0+cu113, 1.11.0+cu115, 1.11.0+rocm4.3.1, 1.11.0+rocm4.5.2, 1.12.0, 1.12.0+cpu, 1.12.0+cu102, 1.12.0+cu113, 1.12.0+cu116, 1.12.0+rocm5.0, 1.12.0+rocm5.1.1, 1.12.1, 1.12.1+cpu, 1.12.1+cu102, 1.12.1+cu113, 1.12.1+cu116, 1.12.1+rocm5.0, 1.12.1+rocm5.1.1, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.0+rocm5.1.1, 1.13.0+rocm5.2)
ERROR: No matching distribution found for torch==1.8.1+cu111
make: *** [Makefile:13: venv] Error 1
```

Any advice? Will try to roll my own conda env if not.

**Comment by sabagh1994** [comment]
Hi Alan, 

Thanks for checking our repo and reporting this issue.

The logs indicate that you're using Python 3.10, and although there are some PyTorch versions available for this particular Python (such as those listed in the log `(from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, ...)`), Version 1.8.1 isn't one of them. We used `python==3.8` and `torch==1.8.1+cu111`.

(A) The easiest way to fix your problem is to use python 3.8 instead. If you visit `https://download.pytorch.org/whl/torch_stable.html` you will see that torch 1.8.1 is only supported by python <= 3.9. To do so, you may need to follow these steps:

1. Remove the existing virtual environment by `rm -rf venv`.
2. If you don't have python 3.8, install it either using Conda, the python website, etc.
3. Activate Python 3.8. If you're using Conda, you should run something like `conda activate python38`.
4. At this point, run `python --version` and make sure that you get a `3.8` (or similar) in the output. If you get a different version, you need to fix that.
5. Now re-run `make venv`.

(B) Alternatively, you can stick to python 3.10. However you need to change your torch version. Also keep in mind that if you want to change the Cuda version as well then Cupy installation has to change. For more information please visit `https://docs.cupy.dev/en/stable/install.html`

**Comment by alanocallaghan** [comment]
Yeah, 3.10 is system python on Ubuntu 22.04.1 LTS. Thanks, venv seems happy with 3.8

**Comment by alanocallaghan** [comment]
Oh, I'm also missing `gdown` if I follow the setup instructions so you should probably mention to pip install it

**Comment by sabagh1994** [comment]
Thanks Alan. I added it.

**Comment by alanocallaghan** [comment]
Sorry to bug you, but I don't know if this is important enough to raise a separate issue. I somehow have problems with cupy versions still, but if I disable the `use_cupy_sum` in `curriculum.py` it seems to run okay (although I suspect my 1070 is going to run out of VRAM at some point...). Is this likely to cause problems?

In case you've seen the cupy error before, I get:
```
ImportError: [...]/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaMemPoolCreate, version libcudart.so.11.0
```

Cheers, looking forward to investigating the method now

**Comment by sabagh1994** [comment]
I would recommend to make cupy work because somewhere in the development process I noticed instabilities with torch.sum. What is your CUDA version? Cupy installation is dependent on the CUDA version.

**Comment by alanocallaghan** [comment]
`nvcc --version` gives `Cuda compilation tools, release 11.5, V11.5.119`

I've tried cupy-cuda115 with torch==1.11.0+cu115 which gets a bit further but ends up giving `module 'cupy' has no attribute 'fromDlpack'` in the `torch_sum` definition

**Comment by sabagh1994** [comment]
Could you please try `from_dlpack` instead of `fromDlpack`?

**Comment by alanocallaghan** [comment]
Ah that seems to have fixed it, along with reinstalling some dependencies, cheers.

What GPU, or what amount of VRAM were you using for these curriculum files? Just so I've an idea of how to tune them for my setup and for the cluster

**Comment by sabagh1994** [comment]
Please read "Run time and memory requirements" in the README. For all of the experiments in the paper I used Tesla V100 with 16GB of memory.
